name: flutter_game
description: "A new flame game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.21.0
  flame_audio: ^2.10.5
  flame_texturepacker: ^4.1.2
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  equatable: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/background_layer1.png
    - assets/images/background_layer2.png
    - assets/images/background_layer3.png
    - assets/images/background_layer4.png
    - assets/images/bullet.png
    - assets/images/enemy_spaceship.png
    - assets/images/smoke_explosion.png
    - assets/audio/background_music.mp3
    - assets/audio/explosion.mp3
    - assets/audio/laser.mp3
